# -------------------------------
#     worldguard-grief-flags
# -------------------------------
# repo: https://github.com/loonybtard/worldguard-grief-flags


# prefix for region flags
# example: grief-allow-wither
#          ^^^^^
wg-flag-prefix: "grief"

# When "true" grief-allow-piston respects setting "prevent_piston_push" from ProtectionStones plugin
ps-respect-prevent-piston-push-setting: true