# -------------------------------
#     worldguard-grief-flags
# -------------------------------
# repo: https://github.com/loonybtard/worldguard-grief-flags


# prefix for region flags
# example: grief-allow-wither
#          ^^^^^
wg-flag-prefix: "grief"