name: WorldGuardGriefFix
main: ru.idleness.worldguardgriefflags.WorldGuardGriefFlagsPlugin
authors:
  - ThaEin
  - Afek
  - OverWrite
version: 4.0
api-version: 1.13
depend: [WorldGuard]
commands:
  wggf: