name: worldguard-grief-flags
main: ru.idleness.worldguardgriefflags.WorldGuardGriefFlagsPlugin
authors:
  - ThaEin
  - Afek (original plugin)
  - OverWrite (original plugin)
version: 1.0.2
api-version: 1.13
depend: [WorldGuard]
softdepend: [ ProtectionStones ]